sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jtfjte0p+tB91twCYo+Aw1aL+8Uuq/S0A1dnydctARGAfyljnfUMTvOrpfnCZV/fhsBpaadGEINjV8gYeACpqc5k3r7GKjWDaX/cajoj1W5bVIuMsABFGO5fz1/nsvhXDRqtq4pWLESpjCXpK5FguDh6ktqyo/o5qIripLvb0fSRe1TR0TxWLjPfv760aEckWblg6nt5/VOVsPHh64+w2e296G931Hzgxq+fmztvM8t32rwaRYPYBdXEmnr4tFMH95zGJGC9BOjfdzDZ7Ozsjfk0zLr+lCw+8ioARMPVgUJzuG6MqSQoaiisZsc1oUSO+O7UWogU/eFGfdA7cAjXOtt8Brmnrp7gopSUIDqFav5EsfNCXW56drBShyjim5vtZtXSWU4zWb0PvzE4PIZtm9IExM88pWShVgvzDL4fpCaNGYbaMvRZieXMigw1FXhZ+nCpX+uCIRMxlOB8NIrtmUkj4Ewwdkd/GfLXDQguhF/BjgM6Lbs7ucsvXh05u3fG8xsF/HI53oX+8uyTyLzuJjUlzW4tdhtlNK3N9fyHAomboEBlAt4/DjKqolT2KTNaVx6Ywehv304QQci91OK7QEkBYaOU90GyAT1KLKSQqoH74xACxWZzuI7EPgQpz8Ra8ZB7TRNn+AaU8z+Pb+terlbGqaGVmAbRFW/GaWYUby4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Rise-of-the-Dutch-Republic-Volume-25-1577-part-II_4827
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy